- id: jsonnet-format
  name: jsonnetfmt
  description: Automatically format jsonnet files.
  entry: jsonnetfmt
  args: [-i]
  language: golang
  files: \.(jsonnet|libsonnet)$
  minimum_pre_commit_version: 2.10.1
- id: jsonnet-lint
  name: jsonnet-lint
  description: Lint jsonnet files.
  entry: jsonnet-lint
  language: golang
  files: \.(jsonnet|libsonnet)$
  minimum_pre_commit_version: 2.10.1
- id: jsonnet-lint_m
  name: jsonnet-lint
  description: Lint jsonnet file.
  entry: xargs -n jsonnet-lint
  language: system
  files: \.(jsonnet|libsonnet)$
  minimum_pre_commit_version: 2.10.1
